### ISSUE TITLE
Set encoding of generated files

### ISSUE THREAD

**Issue by ThePearhead** [bjornvester/xjc-gradle-plugin#15]
I'm using your plugin on a Windows machine.
I want the generated Java files to be UTF-8 encoded. 
However, they turn out to be Windows-1252 (the default encoding on my machine).

I tried to force UTF-8 encoding via the options block. See the following example.
Unfortunately this isn't working.

How can I change the encoding?  

```gradle
xjc {
    xjcVersion = "2.3.3"
    outputJavaDir = file("$buildDir/generated/java")
    outputResourcesDir = file("$buildDir/generated/resources")
    xsdDir = file("src/xsd")
    xsdFiles = fileTree(dir: xsdDir, include: ['*.xsd'])

    options = [
            '-encoding', 'UTF-8']
}
```

**Comment by sal0max** [comment]
Seems this is a known bug in xjc: https://github.com/javaee/jaxb-v2/issues/499

However, the [README.md](https://github.com/bjornvester/xjc-gradle-plugin/blob/master/README.md#choosing-the-file-encoding) in this repo says what to do instead:
> If your schemas contain characters that do not match your default platform encoding (on western versions of Windows, this will probably be CP-1252), set the encoding through the file.encoding property for Gradle. For example, to use UTF-8, put this in your gradle.property file:
>
> `org.gradle.jvmargs=-Dfile.encoding=UTF-8`

So, just add this line to your `gradle.properties`

Bonus info:
Seems this issue in xjc is getting finally solved: https://github.com/eclipse-ee4j/jaxb-ri/pull/1401
Maybe in a future version 3.0.x of xjc this will be fixed for good. For now, go with the `file.encoding` solution.

**Comment by ThePearhead** [comment]
Thanks, that worked!
